### ISSUE TITLE
Bamboo Pipeline doesn't work when Bamboo is accessed via HTTPS

### ISSUE THREAD

**Issue by dancrumb** [CDKGlobal/pipeline#3]
Pipeline throws an error on the Chrome console:

```
[blocked] The page at 'https://bamboo.vodori.com/plugins/servlet/cdpipeline?search=Dan%2520Rumney' was loaded over HTTPS, but ran insecure content from 'http://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.min.js': this content should also be loaded over HTTPS.
```

Since this can't be loaded, the front end later chokes because `ZeroClipboard` is not defined.

**Comment by dancrumb** [comment]
Simple fix... just remove the protocol from your request for ZeroClipboard:

`//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.3.5/ZeroClipboard.min.js`

**Comment by brmakana** [comment]
Thanks dancrumb, we'll see about getting this fix out quickly.

**Comment by dancrumb** [comment]
Sure thing; or I can send you a pull request.

**Comment by brmakana** [comment]
If you'd like to, go ahead! We welcome other committers, that's why we put the plugin on github.

**Comment by dougmessick** [comment]
This fix was pushed to the marketplace in the latest release. https://marketplace.atlassian.com/plugins/com.cobalt.cdpipeline.cdpipeline
